# Generated by Django 2.1.5 on 2019-10-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_tomatoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='predict',
        ),
    ]
