# Generated by Django 2.1.5 on 2019-11-05 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api_tomatoes', '0002_remove_imagedata_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='plantname',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
